name: "build-test"
on:
  push:

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          npm run all
      - uses: ./